import {test,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {onboardingPage} from '../src/render.js';
import {handle} from '../src/worker.js';
const env={SITE_URL:'https://jobs.example.com',SUPABASE_URL:'https://fixture.example',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_test'};
const originalFetch=globalThis.fetch;
afterEach(()=>{globalThis.fetch=originalFetch});
const preferences={user_id:'member',target_roles:['Executive Assistant','Other'],minimum_salary_usd:1000,employment_types:['Full-time'],schedule_preferences:['Flexible/Any'],experience_level:'3–5 years',skills:['Canva','Google Workspace']};
function fixture({fail=false}={}){const writes=[];globalThis.fetch=async(input,init={})=>{const u=new URL(input);if(u.pathname==='/auth/v1/user')return Response.json({id:'member',email:'member@example.com'});if(u.pathname==='/rest/v1/job_preferences'){if(init.method==='POST'){writes.push(JSON.parse(init.body));return fail?Response.json({message:'raw SQL error'},{status:500}):Response.json([preferences]);}return Response.json([preferences]);}if(u.pathname==='/rest/v1/profiles')return Response.json([{id:'member',onboarding_completed:true,plan:'free'}]);if(u.pathname==='/rest/v1/rpc/update_my_profile'){writes.push(JSON.parse(init.body));return Response.json({});}throw Error(u.pathname);};return writes;}
function post(changes={}){const f=new URLSearchParams();for(const [k,v] of Object.entries({...preferences,...changes})){if(k==='user_id')continue;for(const item of Array.isArray(v)?(k==='skills'?[v.join(', ')]:v):[v])f.append(k,item);}return new Request(env.SITE_URL+'/onboarding',{method:'POST',headers:{origin:env.SITE_URL,cookie:'veeays_access=fixture'},body:f});}
test('onboarding keeps every canonical choice, field constraint and saved value',()=>{const html=onboardingPage({preferences});for(const value of ['Executive Assistant','General VA','Customer Support','Social Media','Marketing','Sales','E-commerce','Bookkeeping','Graphic Design','Video Editing','Operations','Web/Development','Other','Full-time','Part-time','Contract/Freelance','Philippines daytime','UK/Europe hours','Australia hours','US hours','Flexible/Any','Entry level','1–2 years','3–5 years','6+ years'])assert.ok(html.includes(`value="${value}"`));assert.match(html,/min="0" max="50000" step="50"/);assert.match(html,/maxlength="1200"/);assert.match(html,/Canva, Google Workspace/);assert.equal((html.match(/class="onboard-step(?: active)?"/g)||[]).length,5);});
test('completion preserves exact preference payload, RPC and job board destination',async()=>{const writes=fixture();const res=await handle(post(),env);assert.equal(res.status,303);assert.equal(res.headers.get('location'),'/?onboarding=complete');assert.deepEqual(writes,[preferences,{new_full_name:null,new_onboarding_completed:true}]);});
test('missing required group still rejects without writes',async()=>{const writes=fixture();const res=await handle(post({schedule_preferences:[]}),env);assert.equal(res.status,303);assert.match(res.headers.get('location'),/Please%20complete/);assert.deepEqual(writes,[]);});
test('save failure never marks onboarding complete or exposes raw backend detail',async()=>{const writes=fixture({fail:true});const res=await handle(post(),env);assert.equal(writes.length,1);assert.match(res.headers.get('location'),/We%20could%20not%20save/);assert.doesNotMatch(onboardingPage({error:'raw SQL error'}),/raw SQL error/);});
test('saved preferences reload through the existing authenticated route',async()=>{fixture();const res=await handle(new Request(env.SITE_URL+'/onboarding',{headers:{cookie:'veeays_access=fixture'}}),env);assert.equal(res.status,200);const html=await res.text();assert.match(html,/value="Flexible\/Any" checked/);assert.match(html,/value="1000"/);assert.match(html,/value="3–5 years" checked/);assert.match(html,/Canva, Google Workspace/);});
