import {test,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {handle} from '../src/worker.js';
import {emailPreferences} from '../src/email-preferences.js';
import {myJobsPage,matchesPage} from '../src/render.js';
import {recovery} from '../src/recovery.js';
const original=globalThis.fetch;afterEach(()=>globalThis.fetch=original);
const env={SITE_URL:'https://veeays.test',SUPABASE_URL:'https://fixture.example',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_test'};
function mock(fail=false){globalThis.fetch=async input=>{const u=new URL(input);if(u.pathname==='/auth/v1/user')return Response.json({id:'member',email:'member@example.com'});if(u.pathname.includes('profiles'))return Response.json([{plan:'pro',plan_status:'active'}]);if(fail)throw Error('private database detail');return Response.json([]);};}
test('missing page and listing retain 404/noindex with accurate context',async()=>{mock();for(const [path,title] of [['/unknown','Let’s find your next step.'],['/jobs/9999','This listing isn’t available.'],['/apply/9999','This listing isn’t available.']]){const r=await handle(new Request(env.SITE_URL+path),env);assert.equal(r.status,404);const html=await r.text();assert.ok(html.includes(title));assert.match(html,/noindex/);assert.match(html,/href="\/jobs"/);}});
test('temporary failure preserves safe GET retry query and Retry-After',async()=>{mock(true);const r=await handle(new Request(env.SITE_URL+'/jobs?q=assistant&page=2'),env);assert.equal(r.status,503);assert.equal(r.headers.get('Retry-After'),'60');const html=await r.text();assert.match(html,/href="\/jobs\?q=assistant&amp;page=2"/);assert.ok(!html.includes('private database detail'));});
test('email load/native save failures retain no-store/503 without switches or false success',async()=>{mock(true);for(const method of ['GET','POST']){const r=await emailPreferences(new Request(env.SITE_URL+'/email-preferences',{method,headers:{cookie:'veeays_access=token',origin:env.SITE_URL,'content-type':'application/x-www-form-urlencoded'},...(method==='POST'?{body:'email_strong_matches=true&daily_digest=false'}:{})}),env);assert.equal(r.status,503);assert.equal(r.headers.get('cache-control'),'no-store');const html=await r.text();assert.match(html,/href="\/email-preferences"/);assert.match(html,/return=%2Femail-preferences/);assert.ok(!html.includes('ep-form'));assert.ok(!html.includes('Preferences saved'));assert.ok(!html.includes('private database detail'));}});
test('failed member loading does not claim saved data is absent',()=>{const html=myJobsPage({loadFailed:true});assert.ok(!html.includes('my-jobs-empty'));assert.ok(!html.includes('tracker-tabs'));assert.match(html,/Reload My Jobs/);const matches=matchesPage({error:'raw backend detail'});assert.ok(!matches.includes('raw backend detail'));assert.ok(!matches.includes('No matches yet'));assert.match(matches,/href="\/matches"/);});
test('recovery URLs and copy escape untrusted request text',()=>{const html=recovery({title:'<script>',copy:'<private>',href:'/jobs?q="<script>',secondaryHref:null});assert.ok(!html.includes('<script>'));assert.match(html,/&quot;&lt;script&gt;/);});
