// Pre-launch copy: review billing, processor disclosures and refund rules before enabling checkout.
const contact = '<p>VeeAys is operated by <strong>Jocelle Parungao</strong>, a sole proprietor based in the Philippines. Website: <a href="https://veeays.com">veeays.com</a>. Email: <a href="mailto:support@veeays.com">support@veeays.com</a>. Phone: <a href="tel:+639758104597">+63 975 810 4597</a>.</p>';
const pages = {
  '/terms': {
    title: 'Terms of Service', description: 'Terms for using VeeAys job discovery, accounts and Pro features.',
    sections: [
      ['Who we are and these terms', contact + '<p>These terms apply when you use VeeAys. Please read them with our <a href="/privacy">Privacy Policy</a> and <a href="/refund-policy">Refund &amp; Cancellation Policy</a>. If you do not agree, stop using the service. Mandatory consumer and privacy rights remain unaffected.</p>'],
      ['Job discovery and applications', '<p>VeeAys provides free public remote-job aggregation for Filipino talent. Accounts can support profiles and preferences, Saved Jobs, an application tracker and personalized matching. VeeAys Pro offers additional discovery features, including Strong Match Alerts and a Daily Job Digest, subject to access and your email preferences.</p><p>We are not the employer for third-party listings. Listings, matching scores and summaries are informational and may be incomplete, outdated or inaccurate. We do not guarantee employment, employer accuracy, job availability, eligibility or hiring outcomes. Verify requirements, compensation and employer identity with the original source before applying.</p><p>Outbound application links take you to third-party services with their own terms and privacy policies. Employers control recruitment and hiring. Saving a job or recording an application in the tracker does not submit an application to an employer.</p>'],
      ['Your account and acceptable use', '<p>Provide accurate account information, keep credentials secure and contact us about suspected unauthorized access. You are responsible for activity you authorize and the profile information and tracker notes you submit. Do not enter unnecessary sensitive information in notes.</p><p>Do not impersonate others, submit unlawful content, spam, attempt unauthorized access, interfere with the service, circumvent access controls or collect other users’ personal information. Use the service only where you can lawfully agree to these terms.</p>'],
      ['VeeAys Pro and payment launch', '<p>The currently advertised Pro price is <strong>₱499/month, cancel anytime</strong>. Payments and Paddle checkout are not live yet. No paid subscription is purchased or renewed through VeeAys at this stage. Pro access shown in an account does not itself authorize a charge.</p><p>Before paid subscriptions launch, we will publish the applicable checkout provider, billing currency, tax treatment, renewal and cancellation details and refund terms. Any recurring payment will require your agreement at checkout. Paddle is a planned provider; it is not currently processing VeeAys transactions. Merchant-of-record and buyer-support disclosures will be added when the integration goes live.</p>'],
      ['Content and intellectual property', '<p>VeeAys branding, design and original software belong to their respective owners. Employer listings, trademarks and linked content remain the property of their owners. You may use the site to discover and manage opportunities, but these terms do not grant ownership of third-party content.</p><p>You retain rights to information you submit and allow us to store and process it to provide the service as described in our Privacy Policy.</p>'],
      ['Availability, suspension and responsibility', '<p>We may update features, correct listings or interrupt service for maintenance or security. Alerts and digests depend on available jobs, matching, settings and email delivery; we do not promise any number of matches or uninterrupted delivery.</p><p>We may restrict or suspend access for misuse, security concerns or legal obligations. Contact support if you believe a restriction is mistaken. You may stop using VeeAys and request account deletion at any time.</p><p>To the extent permitted by applicable law, the service is provided as available without warranties of accuracy or suitability. We are not responsible for employers’ decisions, third-party websites or losses caused by reliance on unverified listings. Nothing excludes responsibility that cannot lawfully be excluded, including applicable consumer rights.</p>'],
      ['Changes, law and contact', '<p>Philippine law governs these terms, subject to mandatory protections and remedies that apply where you live. Contact support first to discuss a concern; this does not restrict access to regulators or courts. Material updates will be communicated through the site or account email where appropriate. The updated date identifies the current version.</p>' + contact]
    ]
  },
  '/privacy': {
    title: 'Privacy Policy', description: 'How VeeAys uses account, preference, job-tracking and session information.',
    sections: [
      ['Who handles your information', contact + '<p>Jocelle Parungao, operating VeeAys, is responsible for personal information used to run this service. This policy covers VeeAys, not the employers or external sites you visit.</p>'],
      ['Information we use', '<p>We process account and authentication information such as email, user ID and profile name; job preferences and onboarding choices; Saved Jobs; application status, dates and notes; matching results and feedback you submit; Pro access status; email-alert and digest preferences; and support messages you send us.</p><p>Requests and sessions can include IP address, browser or device information, request times, cookies and technical error or security records. Public job data includes employer listings, source links and related job information.</p><p>Payments are not live. We do not currently collect payment-card details through VeeAys checkout. Before payment launch, we will explain the provider’s role and the billing or subscription information VeeAys receives.</p>'],
      ['Why we use it', '<p>We use information to authenticate you, maintain your profile and job tracker, personalize matching, manage Pro access, send enabled Strong Match Alerts and Daily Job Digests, answer support requests, diagnose problems and protect the service. Matching uses your preferences and available job information; a match is a recommendation, not an employer’s hiring decision.</p><p>Where applicable, processing is based on providing the service you request, your consent for optional communications, legitimate interests in security and reliable operation, or legal obligations. You can change job-email preferences at <a href="/email-preferences">Email Preferences</a>; operational account and security messages may still be necessary.</p>'],
      ['Providers and external sites', '<p>VeeAys uses Supabase for authentication and stored service data, Cloudflare for hosting and delivery, and Resend for job-email delivery. Providers process the information needed for their function. Configured AI services may organize public employer job text for job-reading features; this is separate from an employer reviewing your application.</p><p>We do not sell your personal information. We may disclose relevant information when legally required, to protect users and the service, or to providers helping operate it. Service providers may process information outside the Philippines; we seek appropriate safeguards for those transfers under applicable law.</p><p>Following an application link shares information with the external site through your visit and anything you submit there. VeeAys does not submit your profile or tracker notes to an employer merely because you save or track a job.</p>'],
      ['Cookies and session data', '<p>Authentication cookies keep you signed in and allow session renewal. A preference-prompt cookie remembers when you dismiss the setup reminder. Technical request information supports delivery, diagnostics and security. Blocking or clearing cookies may sign you out or affect account features.</p>'],
      ['Retention and security', '<p>We keep account, preference and tracker information while needed to provide your account and requested features. You can request deletion through support. Some records may need to remain for security, legal obligations or resolving disputes; backup copies may remain until their normal replacement cycle. We do not promise a fixed deletion period that the service cannot verify.</p><p>We use access controls and other technical protections, but no online system is completely secure. Avoid sending passwords, full payment-card details or unnecessary sensitive information to support.</p>'],
      ['Your choices and rights', '<p>You can update preferences and tracker information through your account. Contact support to request access, correction, deletion, information about processing, or to exercise applicable objection, restriction, portability or consent-withdrawal rights. We may verify your identity before acting. Withdrawal does not invalidate earlier lawful processing; some requests may be limited by legal obligations.</p><p>You may raise privacy concerns with the Philippine National Privacy Commission or another competent authority. The service is intended for people able to use it lawfully; contact us if you believe a child has provided personal information without appropriate authorization.</p>'],
      ['Updates and privacy contact', '<p>We will update this policy when practices change, including before paid checkout launches, and communicate material changes through the site or account email where appropriate.</p>' + contact]
    ]
  },
  '/refund-policy': {
    title: 'Refund & Cancellation Policy', description: 'Current pre-launch payment status and planned VeeAys Pro cancellation terms.',
    sections: [
      ['Current payment status', '<p>VeeAys Pro is currently advertised at <strong>₱499/month, cancel anytime</strong>. Payments and Paddle checkout are <strong>not live yet</strong>. There are no VeeAys checkout purchases, recurring charges or paid billing periods to cancel or refund at this stage. Free public job browsing remains available.</p><p>Paddle is a planned payment provider and does not currently process VeeAys transactions. This page does not describe an active Paddle purchase agreement.</p>'],
      ['Cancellation once paid subscriptions launch', '<p>Before we accept payments, checkout and this policy will disclose the renewal schedule, taxes, cancellation method and payment provider. The planned monthly subscription renews only with your checkout agreement. You will be able to cancel future renewal anytime using the published cancellation method, or contact support for help.</p><p>The planned cancellation takes effect at the end of the paid billing period, with Pro access continuing through that period unless a refund, legal requirement or account restriction changes access. Cancellation and deleting an account are separate actions; use the published billing cancellation method to stop renewal.</p>'],
      ['Refund requests and legal rights', '<p>No refund is currently due for free access or unpaid Pro access. If you believe you have been charged in VeeAys’ name, contact support with the transaction date, amount and receipt reference so we can investigate. Do not send full card details or passwords.</p><p>Before payment launch, we will publish the refund rules that apply to actual purchases, including the provider’s processing role and any applicable withdrawal rights. We do not promise an automatic refund or a specific refund window before those terms are finalized. Cancellation alone will not automatically create a refund entitlement for an already supplied period, except where applicable law or the published purchase terms require it.</p><p>Nothing in this policy limits mandatory consumer rights, remedies for unauthorized charges or rights where a service is not supplied as required by law.</p>'],
      ['Support', contact + '<p>For billing, cancellation or refund help, include your account email and a brief description of the issue. We will explain the next steps without asking for your password.</p>']
    ]
  },
  '/contact': {
    title: 'Contact & Support', description: 'Contact VeeAys for account, job-listing, privacy and Pro support.',
    sections: [
      ['We’re here to help', '<p>For account help, Saved Jobs or application-tracker issues, matching and job-email questions, Pro enquiries or privacy requests, email <a href="mailto:support@veeays.com">support@veeays.com</a> or call <a href="tel:+639758104597">+63 975 810 4597</a>.</p><p>Include the affected page or job link, your account email if relevant, and a short description. Please do not send passwords or sensitive financial information. We do not promise a fixed response time.</p>'],
      ['Listings and applications', '<p>Report broken links, suspicious listings or inaccurate job information with the job URL and the details you noticed. For application status or hiring decisions, contact the employer through its original listing. VeeAys cannot guarantee a response or hiring outcome.</p>'],
      ['Pro and billing enquiries', '<p>Pro is advertised at ₱499/month, cancel anytime. Payments and Paddle checkout are not live yet. See our <a href="/refund-policy">Refund &amp; Cancellation Policy</a> for the current status.</p>'],
      ['Operator details', contact]
    ]
  }
};

export function legalPage(path) {
  const page = Object.hasOwn(pages, path) ? pages[path] : null;
  if (!page) return null;
  return { ...page, body: `<section class="wrap legal-page"><header class="legal-intro"><div class="kicker">VEEAYS · LEGAL &amp; SUPPORT</div><h1>${page.title}</h1><p>${page.description}</p><p class="legal-updated">Updated 5 October 2026</p></header><nav class="legal-nav" aria-label="Legal and support pages">${Object.entries(pages).map(([route, item]) => `<a href="${route}"${route === path ? ' aria-current="page"' : ''}>${item.title}</a>`).join('')}</nav><article class="legal-copy">${page.sections.map(([heading, text]) => `<section><h2>${heading}</h2>${text}</section>`).join('')}</article></section>` };
}
